	tilepal 0, GREEN, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN, RED
	tilepal 0, RED, RED, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, WATER, GREEN, BROWN, BROWN
	tilepal 0, RED, RED, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, YELLOW, BROWN
	tilepal 0, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, GREEN, WATER, WATER, GREEN, BROWN, GREEN, YELLOW
	tilepal 0, YELLOW, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, RED, GREEN, WATER, WATER, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, WATER, GRAY, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, GREEN, GREEN, GREEN, GREEN, BROWN, GREEN, GREEN
	tilepal 0, WATER, GRAY, GREEN, GRAY, GREEN, GREEN, GRAY, GRAY

rept 16
	db $ff
endr

	tilepal 1, BROWN, BROWN, BROWN, RED, RED, RED, RED, RED
	tilepal 1, RED, RED, RED, RED, RED, RED, RED, RED
	tilepal 1, RED, RED, RED, RED, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, GREEN, GRAY, GRAY, BROWN, BROWN, BROWN
	tilepal 1, GREEN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GREEN
	tilepal 1, GREEN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GREEN
	tilepal 1, GREEN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GREEN
	tilepal 1, GREEN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GREEN
	tilepal 1, GREEN, GREEN, ROOF, ROOF, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, GREEN, GREEN, ROOF, ROOF, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
